import {
  IonButton,
  IonContent,
  IonHeader,
  IonTitle,
  IonToolbar,
  IonList,
  IonItem,
  IonLabel,
  IonInput,
  IonIcon,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonBackButton,
  IonButtons,
  IonMenuButton,
  IonItemSliding,
  IonItemOptions,
  IonItemOption,
  IonFab,
  IonFabButton,
  IonMenu,
  IonMenuToggle,
  IonNote,
  IonListHeader,
  IonRouterOutlet,
  IonSplitPane,
  IonApp,
  IonRouterLink
} from '@ionic/angular/standalone';

// Services and controllers
export { AlertController } from '@ionic/angular/standalone';

export const IONIC_COMPONENTS = [
  IonButton,
  IonContent,
  IonHeader,
  IonTitle,
  IonToolbar,
  IonList,
  IonItem,
  IonLabel,
  IonInput,
  IonIcon,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonBackButton,
  IonButtons,
  IonMenuButton,
  IonItemSliding,
  IonItemOptions,
  IonItemOption,
  IonFab,
  IonFabButton,
  IonMenu,
  IonMenuToggle,
  IonNote,
  IonListHeader,
  IonRouterOutlet,
  IonSplitPane,
  IonApp,
  IonRouterLink
];
